# Generated by Django 5.0.2 on 2024-02-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date_and_time',
        ),
    ]
