# Generated by Django 5.0 on 2024-03-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_car_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
